# Generated by Django 5.1.4 on 2025-01-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100, unique=True),
        ),
    ]
