# Generated by Django 5.1.4 on 2025-03-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0004_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
