# Generated by Django 4.2 on 2025-01-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0002_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='app_transactions',
        ),
    ]
