# Generated by Django 4.2 on 2025-01-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0003_alter_transaction_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
