# Generated by Django 5.1.4 on 2025-01-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0002_alter_category_table'),
        ('transactions_app', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories_app.category'),
        ),
    ]
