# Generated by Django 5.1.4 on 2025-01-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0008_alter_transaction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
