# Generated by Django 5.1.4 on 2025-01-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories_app', '0001_initial'),
        ('transactions_app', '0009_rename_amount_transaction_amount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subcategories_app.subcategory'),
        ),
    ]
