# Generated by Django 5.1.4 on 2025-01-09 00:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets_app', '0004_alter_budget_end_date_alter_budget_name_and_more'),
        ('categories_app', '0003_alter_category_category'),
        ('subcategories_app', '0001_initial'),
        ('transactions_app', '0010_transaction_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets_app.budget'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_app.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subcategories_app.subcategory'),
        ),
    ]
