# Generated by Django 4.2 on 2025-01-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='app_budget',
        ),
    ]
