# Generated by Django 5.1.4 on 2025-01-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets_app', '0002_alter_budget_table'),
    ]

    operations = [
    ]
