# Generated by Django 5.1.4 on 2025-01-09 00:40

import budgets_app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets_app', '0003_auto_20250109_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default=budgets_app.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(default='No Budget Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_limit',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]
