# Generated by Django 5.1.4 on 2025-02-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets_app', '0004_alter_budget_end_date_alter_budget_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='app_budgets',
        ),
    ]
