# Generated by Django 5.1.4 on 2025-03-14 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0004_category_user'),
        ('subcategories_app', '0002_subcategory_user_alter_subcategory_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('subcategory_name', 'category', 'user'), name='unique_subcategory_per_category_and_user'),
        ),
    ]
