# Generated by Django 5.1.4 on 2025-03-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories_app', '0003_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=100),
        ),
    ]
